# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-wlcX-p8D3cjLBzf-AgtP9ynv7zMNsp1
"""

import pandas as pd
df = pd.DataFrame({'ism' : ['Abdullo'], 'yosh':['20'], 'familiya ':['Muhammadaliyev']} )
print (df)