# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Juwjcv7Rzvx7l5FOvGwsUkOEnRFhKx1L
"""

import pandas as pd
df = pd.DataFrame({ 'Familiya' : ['ABDUXAKIMOV', 'AZIZIBLOYEV','DO‘LTABOYEV',"ESHBOYEV",'KOMILOVA','MADAMINJONOV','MAMADALIYEV ','MAMATVALIYEV  ',"MIRZAHAMIDOV",'MUHAMMADALIYEV ',"Ne'matova",     ],
                    'Ism' : ['XURSANDBEK','HOJIAKBAR','HOJIAKBAR','ILXOM','DINORA','BAXTIYORJON','ZIKRULLO','DILSHODBEK','JALOLIDDIN','ABDULLO ','DILDORAXON' ],
                    'Yoshi' : [    '19' ,'19','19','19','19','19','19','19','19','19','19'],
                    'Kursi' : [     '2','2' ,'2' ,'2','2','2','2','2','2','2','2']
})
print(df)